LaManuAuto/Controllers/RoleController.cs
using LaManuAuto.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace LaManuAuto.Controllers
{
    public class RoleController : Controller
    {
        private readonly LaManuAutoContext _context;
        public RoleController(LaManuAutoContext context) => _context = context;

        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> Index()
        {
            return _context.Roles != null ?
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'LaManuAutoContext.Roles'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            //var listIdUserPosition = _context.UserRoles.Where(user=>user.RoleId==id);
            ViewBag.userByPosition = _context.UserRoles.Where(user=>user.RoleId==id);
            // SELECT * FROM Users u JOIN UserRoles ur ON u.Id=ur.UserID WHERE ur.RoleID=id
            /*ViewBag.userByPosition = listIdUserPosition.Join(
                _context.Users,
                userRole=>userRole.UserId,
                users => users.Id,
                (userRole, users)
                    => new {
                        ID=users.Id,
                        firstname=users.FirstName,
                        lastname=users.LastName}
                    );*/
            return _context.Roles.Find(id) != null ?
                          View(_context.Roles.Find(id)) :
                          Problem($"Entity set 'LaManuAutoContext.Roles.Find({id})'  is null.");
        }

        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> Manager()
        {
            return _context.Roles != null ?
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'LaManuAutoContext.Roles'  is null.");
        }

        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> Admin()
        {
            return _context.Roles != null ?
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'LaManuAutoContext.Roles'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> Profile(string id)
        {
            return _context.Roles.Find(id) != null ?
                          View(_context.Roles.Find(id)) :
                          Problem($"Entity set 'LaManuAutoContext.Roles.Find({id})'  is null.");
        }
    }
}

LaManuAuto/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaManuAuto.Data;
using LaManuAuto.Models;
using Microsoft.AspNetCore.Authorization;

namespace LaManuAuto.Controllers
{
    public class TagController : Controller
    {
        private readonly LaManuAutoContext _context;

        public TagController(LaManuAutoContext context)
        {
            _context = context;
        }

        // GET: Tag


        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Index()
        {
              return _context.Tags != null ? 
                          View(await _context.Tags.ToListAsync()) :
                          Problem("Entity set 'LaManuAutoContext.Tags'  is null.");
        }

        // GET: Tag/Details/5
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tag/Create
        [Authorize(Policy = "RequireAdminOrManager")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Create([Bind("Id,Shortname,Fullname")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Edit/5
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Shortname,Fullname")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Delete/5
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tags == null)
            {
                return Problem("Entity set 'LaManuAutoContext.Tags'  is null.");
            }
            var tag = await _context.Tags.FindAsync(id);
            if (tag != null)
            {
                _context.Tags.Remove(tag);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
          return (_context.Tags?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LaManuAuto/Controllers/TutorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LaManuAuto.Data;
using LaManuAuto.Models;
using System.Security.Claims;

namespace LaManuAuto.Controllers
{
    public class TutorialController : Controller
    {
        private readonly LaManuAutoContext _context;

        public TutorialController(LaManuAutoContext context)
        {
            _context = context;
        }

        // GET: Tutorials
        public async Task<IActionResult> Index()
        {
            List<Tutorial> tutorials = _context.Tutorials.ToList();
            if (this.User.IsInRole("Administrator") || this.User.IsInRole("Manager") || this.User.IsInRole("User"))
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                string userId = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.Name).Value;

                List<TutorialView> tmp = _context.TutorialView.Where(t => t.UserId == userId).ToList();


                foreach (Tutorial tutorial in tutorials)
                {
                    foreach (TutorialView tutorialView in tmp)
                    {
                        if (tutorialView.TutorialId == tutorial.Id)
                        {
                            tutorial.Viewed = true;
                        }
                    }
                }
            }

            return View(tutorials);
        }

        // GET: Tutorials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tutorials == null)
            {
                return NotFound();
            }

            var tutorial = await _context.Tutorials.Include(t => t.Tags).FirstOrDefaultAsync(t => t.Id == id);
            if (tutorial == null)
            {
                return NotFound();
            }
            if (this.User.IsInRole("Administrator") || this.User.IsInRole("Manager") || this.User.IsInRole("User"))
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                string userId = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.Name).Value;
                TutorialView? view = _context.TutorialView.Where(t => t.TutorialId == id && t.UserId == userId).SingleOrDefault();
                if (view == null)
                {
                    var tmp = new TutorialView();
                    tmp.TutorialId = tutorial.Id;
                    tmp.UserId = userId;
                    _context.TutorialView.Add(tmp);
                    await _context.SaveChangesAsync();
                }
            }
            return View(tutorial);
        }

        // GET: Tutorials/Create
        [Authorize(Policy = "RequireAdminOrManager")]
        public IActionResult Create()
        {
            ViewData["Tags"] = _context.Tags;
            return View();
        }

        // POST: Tutorials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,VideoUrl,CreationDate,ModificationDate")] Tutorial tutorial)
        {
            ICollection<string> keys = HttpContext.Request.Form.Keys;
            List<int> tagsToAdd = new();
            foreach (string key in keys)
            {
                if (key.Contains("Tag_"))
                {
                    tagsToAdd.Add(Int32.Parse(HttpContext.Request.Form[key].ToString()));
                }
            }

            tutorial.Tags = _context.Tags.Where(e => tagsToAdd.Contains(e.Id)).ToList();
            tutorial.CreationDate = DateTime.Now;
            tutorial.ModificationDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(tutorial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tutorial);
        }

        // GET: Tutorials/Edit/5
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tutorials == null)
            {
                return NotFound();
            }

            var tutorial = await _context.Tutorials.Include(t => t.Tags).FirstOrDefaultAsync(t => t.Id == id);
            if (tutorial == null)
            {
                return NotFound();
            }
            ViewData["Tags"] = _context.Tags;
            return View(tutorial);
        }

        // POST: Tutorials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,VideoUrl,CreationDate,ModificationDate")] Tutorial newTutorial)
        {
            if (id != newTutorial.Id)
            {
                return NotFound();
            }
            ICollection<string> keys = HttpContext.Request.Form.Keys;
            List<int> tagsToAdd = new();
            foreach (string key in keys)
            {
                if (key.Contains("Tag_"))
                {
                    tagsToAdd.Add(Int32.Parse(HttpContext.Request.Form[key].ToString()));
                }
            }

            var tutorial = _context.Tutorials.Include(t => t.Tags).Single(u => u.Id == id);
            if (tutorial.Tags != null)
            {
                tutorial.Tags.Clear();
            }
            tutorial.Tags = _context.Tags.Where(e => tagsToAdd.Contains(e.Id)).ToList();
            tutorial.Title = newTutorial.Title;
            tutorial.Description = newTutorial.Description;
            tutorial.VideoUrl = newTutorial.VideoUrl;
            tutorial.ModificationDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tutorial);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TutorialExists(tutorial.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tutorial);
        }

        // GET: Tutorials/Delete/5
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tutorials == null)
            {
                return NotFound();
            }

            var tutorial = await _context.Tutorials
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tutorial == null)
            {
                return NotFound();
            }

            return View(tutorial);
        }

        // POST: Tutorials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "RequireAdminOrManager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tutorials == null)
            {
                return Problem("Entity set 'LaManuAutoContext.Tutorials'  is null.");
            }
            var tutorial = await _context.Tutorials.FindAsync(id);
            if (tutorial != null)
            {
                _context.Tutorials.Remove(tutorial);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TutorialExists(int id)
        {
          return (_context.Tutorials?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LaManuAuto/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LaManuAuto.Areas.Identity.Data
@using Microsoft.AspNetCore.Authorization

@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaManuAuto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LaManuAuto.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="mb-4">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MANU-AUTO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Tutorial" asp-action="Index">Tutorials</a>
                        </li>
                        @if (User.IsInRole("Administrator") || User.IsInRole("Manager") || User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="navbarDropdown" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Manager">Manager</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Admin">Admin</a>
                                    </li>
                                </ul>
                            </li>
                            
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <main role="main" class="pb-2">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-white bg-primary py-3">
        <div class="container">
            &copy; 2022 - LaManuAuto
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>